// Inventory every grid slot; exact names come only from creator-maintained metadata.
const fs=require('fs'),path=require('path'),{PNG}=require('pngjs'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),dir=path.join(root,'assets/catalog');
const image=PNG.sync.read(fs.readFileSync(path.join(root,'assets/source/urizen.png')));
function pixels(im,x,y,w=12){const bits=[],colors=new Set();for(let j=0;j<w;j++)for(let i=0;i<w;i++){const p=((1+y*13+j)*im.width+1+x*13+i)*4,rgb=[...im.data.subarray(p,p+3)];bits.push(+(im.data[p+3]>0&&Math.max(...rgb)>0));if(bits.at(-1))colors.add(rgb.join(','));}return{bits,colors:[...colors]};}
const hash=b=>crypto.createHash('sha1').update(b.join('')).digest('hex').slice(0,12),names=new Map();
for(const family of ['basic','fantasy-medieval','modern','fonts']){
 const meta=JSON.parse(fs.readFileSync(path.join(dir,'source',family+'.json'))),im=PNG.sync.read(fs.readFileSync(path.join(dir,'source',family+'.png')));
 for(const t of meta.tiles||[]){const p=Object.fromEntries(t.properties.map(p=>[p.name,p.value])),key=hash(pixels(im,t.id%meta.columns,Math.floor(t.id/meta.columns)).bits);if(!names.has(key))names.set(key,[]);names.get(key).push({family,...p});}
}
const rows=[
 ['Architectural trim','Doors and stairs','Stonework','Brickwork','Timber and windows','Floor surfaces','Floor surfaces','Rubble','Trees','Plants','Fungi','Cave walls','Water edges','Rocks','Empty','Animals','Creatures','Animals','Food','Ingredients','Prepared food','Accessories','Tableware','Glassware','Tools','Crops','Graves','Graves','Objects','Objects','Objects','Objects','Objects','Objects','Objects','Objects','Objects','Objects','Objects','Objects','Objects','Objects','Objects','Objects','Objects','Objects','Objects','Objects','Objects','Objects'],
 ['Buildings','Buildings','Buildings','Furniture','Potions','Furniture','Weapons','Weapons','Axes and tools','Polearms','Polearms','Weapons','Bows','Armor','Helmets','Magic','Books','Books','Books','Runes','Empty','Furniture','Signs','Furniture','Furniture','Furniture','Furniture','Furniture','Furniture','Furniture','Furniture','Furniture','Furniture','Furniture','Furniture','Furniture','Furniture','Furniture','Furniture','Furniture','Furniture','Furniture','Furniture','Furniture','Magic effects','Banners','Banner composite','Banner composite','Boss composite','Boss composite'],
 ['Industrial architecture','Industrial architecture','Machinery','Machinery','Machinery','Symbols','Transport','Transport','Buildings','Devices','Devices','Devices','Weapons','Weapons','Equipment','Equipment','Equipment','Equipment','Equipment','Equipment','Paperwork','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics','Electronics'],
 [],
 ['Pale humanoid','Pale humanoid variant','Short humanoid','Bearded humanoid','Green humanoid','Orange humanoid','Red humanoid','Teal humanoid','Broad green humanoid','Broad grey humanoid','Skeleton','Aquatic humanoid','Finned humanoid','Armored humanoid','Hunched teal beast','Hunched ochre beast','Orange beast','Violet robed humanoid','Blue robed humanoid','Red skeletal humanoid','Red demon','Blue demon','Slender orange humanoid','Square-headed automaton','Beaked humanoid','Horned beast','Pale automaton','Insect humanoid','Long-snouted humanoid','Stocky armored humanoid','Violet giant','Green quadruped','Dark quadruped','Squat tan beast','Blue aquatic creature','Blue aquatic variant','Red / green pose strips','Red / green pose strips','Grey pose collections','Profession collection','Character collection','Character collection','Bestiary','Character poses','Character poses','Empty','Male movement / arm poses','Female movement / arm poses','Empty','Empty']
];
// Lower bands verified against the full atlas; these supersede broad panel guesses.
rows[0].splice(25,25,...['Trails and particles','Clothing','Armor and outfits','Coats and robes','Boots and gloves','Headwear','Tools and instruments','Furniture','Buildings','Vegetation and landmarks','Tables and counters','Chairs and containers','Papers and terminals','Bones and body parts','Gravestones','Fences and architectural props','Large furniture','Jewelry','Medals','Amulets','Keys and locks','Coins and treasure','Signs and chains','Chains and pendants','Magic symbols']);
rows[1].splice(21,24,...['Chests and shelves','Signs','Gates and fences','Flame effects','Religious objects','Pedestals and ornaments','Pottery and trophies','Jewelry and masks','Plants and magic','Magic particles','Platforms and benches','Empty','Empty','Empty','Empty','Empty','Empty','Empty','Empty','Empty','Empty','Empty','Effects and throne','Magic effects']);
rows[1].splice(0,30,...['Stockades and walls','Buildings','Buildings','Columns and monuments','Potions','Fences','Swords and blades','Axes and tools','Spears and polearms','Polearms','Bows and ranged weapons','Armor','Shields and helmets','Magic and staves','Scrolls and books','Books','Books','Runes','Empty','Chests and shelves','Signs and gallows','Traps and fences','Fire and lamps','Religious furnishings','Furniture and science','Monuments and pottery','Scrolls and trinkets','Flowers and plants','Magic particles','Platforms and benches']);
rows[2].splice(14,36,...['Weapons','Armor and bags','Keys and supplies','Jewelry and medals','Sports and leisure','Accessories','Paperwork','Screens and wires','Electronics','Circuitry','Industrial transport','Industrial transport','Platforms','Machinery','Machinery','Currency','Currency','Currency','Empty','Empty','Trains and vehicles','Control surfaces','Desk lamps and fixtures','Gears and chain','Gears and chain','Gears and chain','Containers','Empty','Empty','Empty','Empty','Empty','Empty','Empty','Empty','Empty']);
rows[3]=['Material patterns','Empty','Material patterns','Empty','Spacecraft','Vehicles','Projectiles and weapons','Devices','Empty','Empty','Empty','Character movement strips','Character movement strips','Character movement strips','Character movement strips','Character movement strips','Celestial bodies','Magic projectiles','Status icons','Stone effects','Spark effects','Empty','Empty','Empty','Arrows and indicators','Projectile effects','Empty','Runic alphabet','Runic alphabet','Runic alphabet','Runic alphabet','Empty','Status icons','Status icons','Status icons','Interface controls','Health and elements','Interface controls','Particle effects','Particle effects','Empty','Empty','Empty','Empty','Latin font','Latin font','Latin font','Punctuation','Latin font variant','Latin font variant'];
const composites=[];for(let i=0;i<10;i++)composites.push({name:['Sorcerer','Horned skull','Serpent','Winged demon','Hollow face','Hooded maw','Spider','Moth','Tentacled elder','Blue wyrm'][i],x:26+i*2,y:48,w:2,h:2,role:'boss candidate'});
for(let i=0;i<12;i++)composites.push({name:'Banner '+i,x:26+i,y:46,w:1,h:2,role:'architecture'});
const animationGroups=[{name:"Slime squash",frames:[[104,42],[105,42]],confidence:"authored pairing; related silhouettes, not an artist-labelled sequence"},{name:'104 walk',frames:[[104,46],[105,46],[106,46]],confidence:'verified pose strip'},{name:'104 arm poses',frames:[[107,46],[108,46],[111,46],[112,46],[113,46]],confidence:'verified poses; timing authored'},{name:'Female walk',frames:[[104,47],[105,47],[106,47]],confidence:'verified pose strip'}];
const entries=[],groups=new Map();
const usage=JSON.parse(fs.readFileSync(path.join(dir,'runtime-selection.json')));
const runtime=new Map();for(const [role,tiles] of Object.entries(usage))for(const {x,y} of tiles)runtime.set(x+','+y,role);

for(let y=0;y<50;y++)for(let x=0;x<206;x++){
 const {bits,colors}=pixels(image,x,y),count=bits.reduce((a,b)=>a+b,0),key=hash(bits),panel=x<26?0:x<52?1:x<78?2:x<104?3:4;
 const kind=!count?'empty':colors.every(c=>c==='255,0,255')?'separator':'sprite';
 const exact=kind==='sprite'?names.get(key)||[]:[],composite=composites.find(c=>x>=c.x&&x<c.x+c.w&&y>=c.y&&y<c.y+c.h);
 const category=kind!=='sprite'?kind:composite?composite.role:panel===4?'Characters':panel===3?'Interface / effects / typography':['Environment / nature','Fantasy / medieval','Modern / science fiction'][panel];
 const family=(exact[0]?[exact[0].group1,exact[0].group2].filter(Boolean).join(' / '):rows[panel][y])||(panel===3?(y<15?'Effects and interface':y<30?'Symbols and typography':'Interface / typography'):'Unreviewed family');
 const entry={id:y*206+x,x,y,kind,category,family,name:exact[0]?[exact[0].group1,exact[0].group2,exact[0].group3,exact[0].orientation,exact[0].index].filter(v=>v!==undefined&&v!=='').join(' / '):composite?composite.name+' part '+(x-composite.x)+','+(y-composite.y):family+' '+x+','+y,confidence:exact.length?'exact silhouette match':composite?'visually verified composite':kind==='sprite'?'region classification; individual role inferred':'grid inventory',silhouette:key,mirror:hash(bits.map((_,i)=>bits[Math.floor(i/12)*12+11-i%12])),colors,exact,composite:composite?.name,animation:animationGroups.filter(g=>g.frames.some(([a,b])=>a===x&&b===y)).map(g=>g.name)};
 entry.runtimeRole=runtime.get(x+','+y)||null;if(panel===4&&y<36){entry.variantFamily='character-row-'+y;entry.equipmentColumn=x;entry.variantNote='Equipment / pose variants across this row; not a verified walk cycle.';}entries.push(entry);if(kind==='sprite'){if(!groups.has(key))groups.set(key,[]);groups.get(key).push(entry.id);}
}
for(const e of entries)if(e.kind==='sprite'){e.variants=groups.get(e.silhouette).filter(id=>id!==e.id);e.mirroredVariants=groups.get(e.mirror)||[];}
const counts={slots:entries.length,sprites:entries.filter(e=>e.kind==='sprite').length,empty:entries.filter(e=>e.kind==='empty').length,separators:entries.filter(e=>e.kind==='separator').length,exactNamed:entries.filter(e=>e.exact.length).length,uniqueSilhouettes:groups.size};
fs.writeFileSync(path.join(dir,'catalog.json'),JSON.stringify({provenance:{atlas:'https://vurmux.itch.io/urizen-onebit-tileset',metadata:'https://github.com/vurmux/urizen/tree/master/urizen/data/tilesets',method:'Every grid slot inventoried. Names transferred by exact binary silhouette; ambiguous matches retained. Region families are inferred, not artist labels. Adjacent equipment variants are not assumed to animate. Composite parts are not standalone creatures.'},counts,composites,animationGroups,entries}));console.log(counts);
