const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),boot=require('./check-game.cjs');
const ctx={fillRect(){},clearRect(){},drawImage(){},save(){},restore(){},translate(){},rotate(){},scale(){}};
const fields=new Map(),document={createElement:()=>({getContext:()=>ctx}),getElementById:id=>{if(!fields.has(id))fields.set(id,{getContext:()=>ctx,setAttribute(){}});return fields.get(id);}};
const code=require('./content-data.cjs')()+require('./landmark-data.cjs')()+['room','actions','world','combat'].map(n=>fs.readFileSync('src/'+n+'.js','utf8')).join('\n')+fs.readFileSync('src/game.js','utf8').split('function choose(')[0];
const g=vm.runInNewContext('const DEV=false,assets={actor:160,pantry:0,weapon:24,enemies:27,weaponCount:3,enemyCount:8,bosses:35,letters:""};'+code+';({reset,hitEnemy,enterRoom,get score(){return score},setHealth(n){health=n},nextFloor(){level++;world=makeLevel(1,level);chamber=0;enterRoom()}})',{atob,document});
g.reset();assert.equal(g.score,0);const e={hp:1};g.hitEnemy(e,1);assert.equal(g.score,10);g.hitEnemy(e,1);assert.equal(g.score,10,'dead enemy cannot score twice');
g.nextFloor();const boss={boss:true,hp:20,x:1,y:1,kind:0,pattern:0};g.hitEnemy(boss,1);assert.equal(g.score,10,'damage alone gives no score');g.hitEnemy(boss,20);assert.equal(g.score,110);g.nextFloor();assert.equal(g.score,110,'floor transition preserves score');g.setHealth(0);g.hitEnemy({hp:1},1);assert.equal(g.score,110,'score freezes on death');g.reset();assert.equal(g.score,0,'new run resets score');
for(const file of ['dist/index.html','dev/play.html']){const p=boot(file,undefined,false,false);assert(!p.lettering.some(x=>/^SCORE/.test(x)),'score hidden alive');p.goDungeon();for(let i=0;i<3600&&p.pose!==38;i++)p.tick();assert.equal(p.pose,38);assert(p.lettering.some(x=>/^SCORE \d+$/.test(x)),'score appears on death');p.key('keydown','r');p.key('keyup','r');p.tick();assert(!p.lettering.some(x=>/^SCORE/.test(x)),'score hidden after restart');}
console.log('PASS score: kills only, once per kill, boss value, floor persistence, death freeze and death-only display in both builds');
