const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),boot=require('./check-game.cjs');
const ctx={fillRect(){},clip(){},rect(){},beginPath(){},clearRect(){},drawImage(){},save(){},restore(){},translate(){},rotate(){},scale(){}};
const fields=new Map(),document={createElement:()=>({getContext:()=>ctx}),getElementById:id=>{if(!fields.has(id))fields.set(id,{getContext:()=>ctx,setAttribute(){}});return fields.get(id);}};
const code=require('./content-data.cjs')()+['room','actions','world','combat'].map(n=>fs.readFileSync('src/'+n+'.js','utf8')).join('\n')+fs.readFileSync('src/game.js','utf8').split('function choose(')[0];
const g=vm.runInNewContext('const DEV=false,assets={entrance:'+JSON.stringify(require('../assets/entrance.json'))+',actor:160,pantry:0,weapon:24,enemies:27,weaponCount:3,enemyCount:8,bosses:35,letters:""};'+code+';({reset,makeLevel,points:()=>score,kill(e){hitEnemy(e,1);},health(n){health=n;},song:()=>world.song,notes(seed,depth){world=depth?makeLevel(seed,depth):makeEntrance();const out=[];audio={currentTime:0,destination:{},createOscillator(){const o={frequency:{},connect(){},start(){out.push(o.frequency.value)},stop(){}};return o},createGain(){return{gain:{setValueAtTime(){},exponentialRampToValueAtTime(){}},connect(){}}}};beat=0;beatClock=0;for(let i=0;i<1200;i++)musicTick(1/60);audio=null;return out.join()}})',require('./canvas-dom.cjs')({atob,document}));
// Every floor rolls its own song: different seeds and depths sound different, the same floor repeats exactly.
const songs=new Set();for(let seed=0;seed<20;seed++)for(const depth of [1,2]){const a=g.notes(seed,depth);assert.equal(a,g.notes(seed,depth),'a floor replays its own song');songs.add(a);}assert(songs.size>=38,'floors get distinct songs: '+songs.size);
const entranceSongs=new Set();for(let i=0;i<20;i++)entranceSongs.add(g.notes(i,0));assert(entranceSongs.size>=19,'Room Zero generates different music between runs');
g.reset();const enemy={hp:1,x:5,y:5};g.kill(enemy);assert.equal(g.points(),10);g.kill(enemy);assert.equal(g.points(),10,'dead enemies cannot score twice');g.health(0);g.kill({hp:1,x:6,y:5});assert.equal(g.points(),10,'score freezes on death');g.reset();assert.equal(g.points(),0,'new run resets score');
for(const file of ['dist/index.html','dev/play.html'])for(const key of ['q',' ','ArrowLeft']){const p=boot(file,undefined,false,false,4);p.goDungeon();assert(!p.lettering.some(x=>/SCORE/.test(x)),'score stays hidden while alive');for(let i=0;i<3600&&p.pose!==38;i++)p.tick();assert.equal(p.pose,38);assert(p.lettering.some(x=>/^SCORE \d+$/.test(x)));assert(p.lettering.includes('Press any key to revive'));p.key('keydown',key,p.fields.game,{repeat:true});p.tick();assert.equal(p.pose,38,'held key repeat cannot dismiss death');p.key('keyup',key);p.key('keydown',key);p.key('keyup',key);p.tick();assert.notEqual(p.pose,38);assert.equal(p.x,36,'revive starts a fresh run without moving');assert(!p.lettering.some(x=>/SCORE/.test(x)),'revive hides score');}
console.log('PASS songs, death-only score, frozen scoring, reset and any-key revival in both builds');
