const acorn=require('acorn');
const eligible=catalog=>{const w=catalog.weapons[0];return catalog.weapons.length===1&&w.id==='fist'&&!catalog.bosses.length&&(w.type??0)===0&&w.attack?.count===0&&(w.damage??1)===1&&(w.reach??1)===1;};
module.exports=(source,catalog)=>{
 if(!eligible(catalog))return source;
 const replace=(name,body)=>{const n=acorn.parse(source,{ecmaVersion:2020}).body.find(n=>n.type==='FunctionDeclaration'&&n.id.name===name);if(!n)throw Error('Missing '+name);source=source.slice(0,n.body.start)+'{'+body+'}'+source.slice(n.body.end);};
 const body=name=>{const n=acorn.parse(source,{ecmaVersion:2020}).body.find(n=>n.type==='FunctionDeclaration'&&n.id.name===name);return source.slice(n.body.start+1,n.body.end-1);};
 replace('worldAttack',`blows.push({a:actionStates.attack.direction,age:-.08,hit:0});tone(weaponRules[weapon][W_PITCH],.045);`);
 replace('blowShape',body('blowShape').slice(body('blowShape').indexOf('const p='),body('blowShape').indexOf('\n const k=')).replace(/;}\s*$/,';'));
 replace('hitBlow',`if(b.age<0||previousAge>=.16)return;const {x,y,a,start,end,radius}=blowShape(b,previousAge+(b.age-previousAge)),c=Math.cos(a),s=Math.sin(a);for(const e of room.enemies)if(e.hp>0&&!b.hit.includes(e)&&capsuleHit(x+c*start,y+s*start,x+c*end,y+s*end,radius,e)&&clearShot(player,e)){b.hit.push(e);hitEnemy(e,b.damage);}`);
 replace('drawCombat',body('drawCombat').replace(/ \/\/ Anchor[\s\S]*?(?= if\(radiation\))/,'').replace('ctx.globalAlpha=t<f.burn-.5?.65:1;','ctx.globalAlpha=t<f.burn-.5?.65:1;'));
 replace('drawActor',body('drawActor').replace("actionFrame()||((dash||blows.some(b=>b.kind!==0&&b.kind!==5))?2:0),weaponType=weaponRules[weapon][W_TYPE],left=DEV&&Math.cos(facing)<0,jab=blade?0:weaponType===5&&action?.type==='attack'?3-frame:0", "actionFrame(),left=DEV&&Math.cos(facing)<0").replace(' x+=Math.round(Math.cos(facing)*jab);y+=Math.round(Math.sin(facing)*jab);',''));
 replace('tickCombat',body('tickCombat').replace('if(b.kind===6&&b.age>.24)movePlayer(room.cells,player,Math.cos(b.a),Math.sin(b.a),Math.max(0,Math.min(b.age,.42)-Math.max(previous,.24)),28);','').replace('hitBlow(b,b.kind===6?from:null,Math.max(0,previous));','hitBlow(b,null,Math.max(0,previous));').replace('b.kind===0&&previous','previous').replace('(b.kind===0?.21:b.kind===6?.42:b.kind===3?.18:.22)','.21').replace('if(dash?.age>=.42)dash=null;','').replace(/  if\(f.damage\)\{[^\n]*\}\n  else if/, '  if'));
 replace('cast',body('cast').replace("shape===4?friendly?{x:p.x+Math.cos(a)*4,y:p.y+Math.sin(a)*4}:player:p",'shape===4?player:p').replace(',damage:friendly?2:0,hit:[]','').replace("tone(friendly?430:170,.09,'triangle',.015)","tone(170,.09,'triangle',.015)"));
 replace('extinguish',body('extinguish').replace('fields=fields.filter(f=>f.damage)','fields=[]'));
 replace('fire',`if(shots.length>=96)return;const s={x:p.x,y:p.y,dx:Math.cos(a)*speed,dy:Math.sin(a)*speed,life};shots.push(s);return s;`);
 const emit='const s=fire(p,a+(flags&4?j/count*Math.PI*2:(j-(count-1)/2)*spread),speed,damage,life,friendly,!!(flags&2));';
 if(!body('volley').includes(emit))throw Error('Review enemy emitter');
 replace('volley',body('volley').replace('j<count;j++','j<count&&shots.length<96;j++').replace(emit,'const angle=a+(flags&4?j/count*Math.PI*2:(j-(count-1)/2)*spread),s={x:p.x,y:p.y,dx:Math.cos(angle)*speed,dy:Math.sin(angle)*speed,life};shots.push(s);'));
 replace('tickWorld',body('tickWorld').replace(/s.age\+=dt;s.life-=dt;[^\n]*\n  if\(\(s.traits&2\)[^\n]*\n/,'s.life-=dt;\n').replace('tip=s.art>=0?0:.3,radius=s.art>=0?.3:.09','tip=.3,radius=.09').replace(/   if\(s.damage\)\{[^\n]*\}\n   else if/,'   if'));
 if(catalog.enemies.every(e=>(e.attack.speed??3.2)<=12))replace('tickWorld',body('tickWorld').replace('const steps=Math.max(1,Math.ceil(Math.hypot(s.dx,s.dy)*dt/.2));','const steps=1;'));
 replace('drawWorld',body('drawWorld').replace('s.art>=0?Math.round(s.age*32/Math.PI)*Math.PI/2:(dir+diagonal)*Math.PI/4','(dir+diagonal)*Math.PI/4').replace('s.art>=0?assets.weapon+s.art:assets.mini+(diagonal?3:4)','assets.mini+(diagonal?3:4)'));
 replace('drawLoot',body('drawLoot').replace('const w=weaponRules[o.value];','').replace('o.kind===4?assets.armors+o.value:assets.weapon+w[W_SPRITE]','assets.armors+o.value'));
 replace('strike',`const b={a,age:-delay,hit:0};blows.push(b);return b;`);
 replace('hitEnemy',`if(e.hp<=0)return;e.hp=0;tone(75,.12,'triangle',.04);if(health)score+=10;objects.push({x:e.x,y:e.y,kind:1,value:Math.random()*5|0});`);
 replace('hitBlow',body('hitBlow').replace('&&!b.hit.includes(e)','').replace('b.hit.push(e);hitEnemy(e,b.damage)','b.hit=1;hitEnemy(e,2)'));
 replace('blowShape',body('blowShape').replaceAll('(b.reach??1.6)','1.6'));
 replace('drawStarter',body('drawStarter').replace('const active=blows.filter(b=>b.kind===0);','const active=blows;').replace("weapon===0?[{kind:0,a:facing,age:-.08,reach:1.6,hit:[]}]:[]","[{a:facing,age:-.08}]").replace('b.hit.length','b.hit'));
 source=source.replaceAll('blows.find(b=>b.kind===0)','blows[0]').replaceAll('e.flash=Math.max(0,(e.flash||0)-dt);','').replaceAll('ctx.globalAlpha=e.flash?.35:1;','');
 source=source.replace('function hitBlow(b,from,previousAge=b.age)','function hitBlow(b,previousAge=b.age)').replace('hitBlow(b,null,Math.max(0,previous))','hitBlow(b,Math.max(0,previous))');
 return source;
};
module.exports.eligible=eligible;
